# Generated by Django 4.2.5 on 2023-09-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_dislikes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
